// For mainReducer

export const SET_USER = 'SET_USER'
export const SET_ORDERS = 'SET_ORDERS'
export const SET_PLAY_SOUND = 'SET_PLAY_SOUND'
export const SET_ACTIVE_ORDER = 'SET_ACTIVE_ORDER'
export const SET_ACTIVE_INDEX = 'SET_ACTIVE_INDEX'
export const SET_ACTIVE_BARCODE = 'SET_ACTIVE_BARCODE'
export const SET_ORDER_STARTED = 'SET_ORDER_STARTED'
export const SET_MODAL_VISIBLE = 'SET_MODAL_VISIBLE'
export const SET_ORDER_CANCEL_MODAL_VISIBLE = 'SET_ORDER_CANCEL_MODAL_VISIBLE'
export const SET_PRIVIOUS_OPERATION = 'SET_PRIVIOUS_OPERATION'
export const SET_CONFIRMATION = 'SET_CONFIRMATION'
export const SET_MATERIALS_ARR = 'SET_MATERIALS_ARR'
export const SET_MATERIALS_CONDITION = 'SET_MATERIALS_CONDITION'
export const SET_MATERIALS_VALUE = 'SET_MATERIALS_VALUE'
export const SET_SHOW_MATERIALS_COMPONENT = 'SET_SHOW_MATERIALS_COMPONENT'
export const SET_EQUIPMENT_ARR = 'SET_EQUIPMENT_ARR'
export const SET_IS_EQUIPMENT_LOADING = 'SET_IS_EQUIPMENT_LOADING'
export const SET_EQUIPMENT_VISIBLE = 'SET_EQUIPMENT_VISIBLE'
export const SET_SELECTED_ITEMS_CHECKED = 'SET_SELECTED_ITEMS_CHECKED'
export const SET_SELECTED_ITEMS_UNCHECKED = 'SET_SELECTED_ITEMS_UNCHECKED'
export const SET_FINISH_ORDER_PARAMS = 'SET_FINISH_ORDER_PARAMS'

// For headerReducer

export const SET_IS_USER_MENU_MODAL = 'SET_IS_USER_MENU_MODAL'

// For messagesReducer

export const SET_MESSAGES = 'SET_MESSAGES'

// For activeOrderReducer

export const SET_SOUND = 'SET_SOUND'

// For techMapsReducer

export const SET_MAPS_ARR = 'SET_MAPS_ARR'
export const SET_MODAL_VISIBLE_TECH_MAPS = 'SET_MODAL_VISIBLE_TECH_MAPS'
export const SET_ITEM = 'SET_ITEM'

// For barCodeReducer

export const SET_HAS_PERMISSION = 'SET_HAS_PERMISSION'
export const SET_SCANNED = 'SET_SCANNED'
export const SET_BARCODE = 'SET_BARCODE'
export const SET_BOUNDS = 'SET_BOUNDS'

// For equipmentItemReducer

export const SET_IS_CHECKED_ARR = 'SET_IS_CHECKED_ARR'
export const SET_IS_CHECKED = 'SET_IS_CHECKED'
export const SET_IS_LOADING = 'SET_IS_LOADING'

// For newMessageItemReducer

export const SET_NEW_MESSAGE = 'SET_NEW_MESSAGE'

// For orderReducer

export const SET_IMG_TAG = 'SET_IMG_TAG'

// For userMenuModalReducer

export const SET_IS_COMPLETE_WORK_SHIFT_VISIBLE =
  'SET_IS_COMPLETE_WORK_SHIFT_VISIBLE'
export const SET_USER_MENU_ORDERS = 'SET_USER_MENU_ORDERS'
export const SET_TEMP_DETAIL = 'SET_TEMP_DETAIL'
export const SET_CREATED_ORDER_ID = 'SET_CREATED_ORDER_ID'

// For authReducer

export const SET_LOGIN = 'SET_LOGIN'
export const SET_PASSWORD = 'SET_PASSWORD'
export const SET_APP_IS_READY = 'SET_APP_IS_READY'
export const SET_SHOW_ERROR = 'SET_SHOW_ERROR'

// For startFinishButtonReducer

export const SET_IS_EQUIPMENT_EMPTY = 'SET_IS_EQUIPMENT_EMPTY'

// For errorReduser

export const SET_IS_ERROR_COMPONENT_VISIBLE = 'SET_IS_ERROR_COMPONENT_VISIBLE'
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE'
